#!env php
<?php
/* vim: set expandtab tabstop=4 shiftwidth=4: */

/**
 * PHP versions 4 and 5
 *
 * Copyright (c) 2005-2007 KUBO Atsuhiro <iteman@users.sourceforge.net>,
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * @package    Stagehand_TestRunner
 * @copyright  2005-2007 KUBO Atsuhiro <iteman@users.sourceforge.net>
 * @license    http://www.opensource.org/licenses/bsd-license.php  BSD License (revised)
 * @version    SVN: $Id: package.php 19 2007-06-19 09:05:41Z iteman $
 * @since      File available since Release 0.5.0
 */

error_reporting(E_ALL);

if (file_exists(dirname(__FILE__) . '/../Stagehand/TestRunner/PHPUnitTestRunner.php')) {
    set_include_path(realpath(dirname(__FILE__) . '/..') . PATH_SEPARATOR . get_include_path());
}

require_once 'Stagehand/TestRunner/PHPUnitTestRunner.php';
require_once 'Console/Getopt.php';

if (!array_key_exists('argv', $_SERVER)) {
    echo 'ERROR: either use the CLI php executable, or set register_argc_argv=On in php.ini';
    exit(1);
}

$argv = Console_Getopt::readPHPArgv();
array_shift($argv);
$options = Console_Getopt::getopt2($argv, "hVR");
if (PEAR::isError($options)) {
    echo 'ERROR: ' . preg_replace('/^Console_Getopt: /', '', $options->getMessage()) . "\n";
    displayUsage();
    exit(1);
}

$directory = null;
$isRecursive = false;
foreach ($options as $option) {
    if (!count($option)) {
        continue;
    }

    if (count($option) == 1) {
        if (is_array($option[0])) {
            switch ($option[0][0]) {
            case 'h':
                displayUsage();
                exit(1);
            case 'V':
                displayVersion();
                exit(1);
            case 'R':
                $isRecursive = true;
                break;
            }
        } else {
            $directory = "{$option[0]}TestCase.php";
        }
    }
}

if (!$isRecursive) {
    if (is_null($directory)) {
        $directory = getcwd();
    }

    $result = Stagehand_TestRunner_PHPUnitTestRunner::run($directory);
} else {
    $directory = getcwd();
    $result = Stagehand_TestRunner_PHPUnitTestRunner::runAll($directory);
}

$runs = $result->runCount();
$passes = count($result->passedTests());
$failures = $runs - $passes;

printf('### Results ###
%s
Runs     : %d
Passes   : %d (%d%%)
Failures : %d (%d%%), %d errors, %d failures
',
       $result->toString(),
       $runs,
       $passes, $runs ? $passes / $runs * 100 : 0,
       $failures, $runs ? $failures / $runs * 100 : 0,
       $result->errorCount(), $result->failureCount()
       );

exit(0);

function displayUsage()
{
    echo "Usage: {$_SERVER['SCRIPT_NAME']} [OPTION]... [TESTCASE]

Options:
  -h
        display this help and exit
  -V
        display version information and exit
  -R
        run test cases recursively

With no TESTCASE, run all test cases in the current directory.
";
}

function displayVersion()
{
    echo "Stagehand_TestRunner @package_version@

Copyright (c) 2006-2007 KUBO Atsuhiro <iteman@users.sourceforge.net>,
All rights reserved.
";
}

/*
 * Local Variables:
 * mode: php
 * coding: iso-8859-1
 * tab-width: 4
 * c-basic-offset: 4
 * c-hanging-comment-ender-p: nil
 * indent-tabs-mode: nil
 * End:
 */
?>
